### ISSUE TITLE
Access to stored vector

### ISSUE THREAD

**Issue by rafael-aero** [nmslib/hnsw#12]
Hi @yurymalkov & @searchivarius,

After reading a bit the code, it seems like it is storing the vector data for each element in internal memory structure - is there a way of accessing the data after it has been indexed?

Does this memory location changes when new items are added? Or one could fetch the vector data from the location it was stored in the first place?

Thanks!

**Comment by yurymalkov** [comment]
Hi @rafael-aero,

You can access the data by using the method `char *getDataByInternalId(tableint internal_id)` which returns the pointer to the first element in the vector. To get an internal ID of an element you should store the result of HNSW's `addPoint(void *data_point, labeltype label, int level)`.

Right now the element's internal IDs never change. But this probably might be changed in the future.

**Comment by rafael-aero** [comment]
awesome, thanks for the super quick reply 👍 
I'll keep in mind for future versions to check if this is still the case.

**Comment by glennkroegel** [comment]
Is there a way of doing this with the python bindings? 

The method nmslib.getDataPoint(index, i) doesn't seem to work if you are loading a previously saved index. Executing nmslib.getDataPointQty(index) returns 0 even if the data is loaded (as index.knnQuery **does** return results).

**Comment by yurymalkov** [comment]
@glennkroegel Should be so. I'll into it.

**Comment by yurymalkov** [comment]
@glennkroegel It seems that you are referencing nmslib, not hnswlib. hnswlib has a different function with similar functionality (`get_items`). It also should work after saving/loading the index without any problems.

In nmslib's hnsw you need to reload all elements separately from loading the index itself in order to access them (hope @searchivarius will correct me if I am wrong). This is because hnsw in nmslib is using its own data structures.
